Revert "Refactor commands into packages and finish up the base model for all …" (#399)
This reverts commit a2ab9dbe64f39e7c983e41805038a58ee8e10017.

diff --git a/.github/workflows/gochecks.yml b/.github/workflows/gochecks.yml
--- a/.github/workflows/gochecks.yml
+++ b/.github/workflows/gochecks.yml
@@ -6,7 +6,7 @@ on:
       - master
 
 jobs:
-  Golangci-Lint:
+  Go-Lint:
     runs-on: ubuntu-latest
 
     steps:
@@ -14,17 +14,22 @@ jobs:
       - name: Setup Go
         uses: actions/setup-go@v2
         with:
-          go-version: "1.21"
+          go-version: '1.14.0'
 
       - name: Install dependencies
         run: |
           go version
-          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
+          go get -u golang.org/x/lint/golint
 
-      - name: Run golangci-lint
+      - name: Run Lint
         run: |
-          golangci-lint run cmd/...
-
+          golint_files=$(golint cmd)
+          if [[ -n ${golint_files} ]]; then
+              echo 'fix the following linting errors:'
+              echo "${golint_files}"
+              exit 1
+          fi
+          exit 0
 
   Go-Fmt:
     runs-on: ubuntu-latest
@@ -34,7 +39,7 @@ jobs:
       - name: Setup Go
         uses: actions/setup-go@v2
         with:
-          go-version: "1.21"
+          go-version: '1.14.0'
 
       - name: Run fmt
         run: |
